articles = [
"A new heat engine with no moving parts is as efficient as a steam turbine. Engineers at MIT and the National Renewable Energy Laboratory (NREL) have designed a heat engine with no moving parts. Their new demonstrations show that it converts heat to electricity with over 40 percent efficiency — a performance better than that of traditional steam turbines. The heat engine is a thermophotovoltaic (TPV) cell, similar to a solar panel’s photovoltaic cells, that passively captures high-energy photons from a white-hot heat source and converts them into electricity. The team’s design can generate electricity from a heat source of between 1,900 to 2,400 degrees Celsius, or up to about 4,300 degrees Fahrenheit."
"The researchers plan to incorporate the TPV cell into a grid-scale thermal battery. The system would absorb excess energy from renewable sources such as the sun and store that energy in heavily insulated banks of hot graphite. When the energy is needed, such as on overcast days, TPV cells would convert the heat into electricity, and dispatch the energy to a power grid."
"With the new TPV cell, the team has now successfully demonstrated the main parts of the system in separate, small-scale experiments. They are working to integrate the parts to demonstrate a fully operational system. From there, they hope to scale up the system to replace fossil-fuel-driven power plants and enable a fully decarbonized power grid, supplied entirely by renewable energy."
"Thermophotovoltaic cells were the last key step toward demonstrating that thermal batteries are a viable concept, says Asegun Henry, the Robert N. Noyce Career Development Professor in MIT’s Department of Mechanical Engineering. “This is an absolutely critical step on the path to proliferate renewable energy and get to a fully decarbonized grid.”"
"Henry and his collaborators have published their results today in the journal Nature. Co-authors at MIT include Alina LaPotin, Kevin Schulte, Kyle Buznitsky, Colin Kelsall, Andrew Rohskopf, and Evelyn Wang, the Ford Professor of Engineering and head of the Department of Mechanical Engineering, along with collaborators at NREL in Golden, Colorado."
"Jumping the gap"
"More than 90 percent of the world’s electricity comes from sources of heat such as coal, natural gas, nuclear energy, and concentrated solar energy. For a century, steam turbines have been the industrial standard for converting such heat sources into electricity."
"On average, steam turbines reliably convert about 35 percent of a heat source into electricity, with about 60 percent representing the highest efficiency of any heat engine to date. But the machinery depends on moving parts that are temperature- limited. Heat sources higher than 2,000 degrees Celsius, such as Henry’s proposed thermal battery system, would be too hot for turbines."
"In recent years, scientists have looked into solid-state alternatives — heat engines with no moving parts, that could potentially work efficiently at higher temperatures."
"“One of the advantages of solid-state energy converters are that they can operate at higher temperatures with lower maintenance costs because they have no moving parts,” Henry says. “They just sit there and reliably generate electricity.”"
"Thermophotovoltaic cells offered one exploratory route toward solid-state heat engines. Much like solar cells, TPV cells could be made from semiconducting materials with a particular bandgap — the gap between a material’s valence band and its conduction band. If a photon with a high enough energy is absorbed by the material, it can kick an electron across the bandgap, where the electron can then conduct, and thereby generate electricity — doing so without moving rotors or blades."
"To date, most TPV cells have only reached efficiencies of around 20 percent, with the record at 32 percent, as they have been made of relatively low-bandgap materials that convert lower-temperature, low-energy photons, and therefore convert energy less efficiently."
"Catching light",

"For the software industry the use of strategic market and competitive intelligence has not been particularly well executed by many vendors. MI and CI for software vendors differs greatly from the more established practices for CPG, Pharma or manufacturing – often what works well for these other industries has little relevance for software vendors. The main difference: the intensely fast pace of constant change for most of the software industry. 'Time' is measured in nanoseconds. As such the software industry requires a greater focus on MI and CI, but often actual practice does not include the most beneficial aspects. "
"Market Intelligence is essential for creating strong product strategy and for fine-tuning that strategy as industries, markets, customers, the product space, and competitors evolve over time – again usually very small windows of time. Core decisions for businesses must be based on reasonable understanding of significant and likely future events – what the potential impact could be, good and bad. Market intelligence is the dynamic means for uncovering the right future-pointing intelligence as early as possible, averting 'nasty surprises' and discovering new opportunities."
"Strategic market Intelligence differs from business research (and traditional business intelligence) through context -- a certain mindset held while the research and analysis phases are done. The market intelligence professional always has in mind the organization, its business and product space, the industry, customers and target markets, and the drivers behind the need for intelligence. It's an ongoing sense of the impact of what could be uncovered -- the ramifications of what seemingly unconnected items of intelligence could mean for the company. It ensures that business decisions and product direction are customer-focused, market-driven, and reality-based."
"Where software companies go wrong with MI and CI efforts is limiting activities to directly supporting sales in tactical ways, focusing only on pointless programs for 'killing the competition', and endless feature/function battles that are meaningless in today's commoditized markets for software solutions. Another wrong turn has been the adherence to Porter's Five Forces as a model for product strategy and for market and competitive intelligence, undoubtedly influenced by MBA school curricula in the eighties and nineties, much of which has now proven useless to many enterprises.",

"Developing brain needs cannabinoid receptors after birth"
"Cannabinoid receptors help the brain’s dopamine system establish key connections after birth, a new mouse study suggests."
"Doctors warn that marijuana use during pregnancy may have harmful effects on the development of a fetus, in part because the cannabinoid receptors activated by the drug are known be critical for enabling a developing brain to wire up properly. Now, scientists at MIT’s McGovern Institute for Brain Research have learned that cannabinoid receptors’ critical role in brain development does not end at birth."
"In today's online issue of eNeuro, scientists led by McGovern investigator Ann Graybiel report that mice need the cannabinoid receptor CB1R to establish connections within the brain’s dopamine system that take shape soon after birth. The finding raises concern that marijuana use by nursing moms, who pass the CB1R-activating compound THC to their infants when they breastfeed, might interfere with brain development by disrupting cannabinoid signaling."
"“This is a real change to one of the truly important systems in the brain — a major controller of our dopamine,” says Graybiel, who is an Institute Professor and a faculty member in the Department of Brain and Cognitive Sciences. Dopamine exerts a powerful influence over our motivations and behavior, and changes to the dopamine system contribute to disorders from Parkinson’s disease to addiction. Thus, the researchers say, it is vital to understand whether postnatal drug exposure might put developing dopamine circuits at risk."
"Cannabinoid receptors in the brain are important mediators of mood, memory, and pain. Graybiel’s lab became interested in CB1R due to their dysregulation in Huntington’s and Parkinson’s diseases, both of which impair the brain’s ability to control movement and other functions. While investigating the receptor’s distribution in the brain, they discovered that in the adult mice, CB1R is abundant within small compartments within the striatum called striosomes. The receptor was particularly concentrated within the neurons that connect striosomes to a dopamine-rich area of the brain called the substantia nigra, via structures that Graybiel’s team has dubbed striosome-dendron bouquets."
"Striosome-dendron bouquets are easy to overlook within the densely connected network of the brain. But when the cells that make up the bouquets are labeled with a fluorescent protein, the bouquets become visible — and their appearance is striking, says Jill Crittenden, a research scientist in Graybiel’s lab.",

"Elon Musk offers to buy Twitter for $43 billion, so it can be ‘transformed as private company’"
"Elon Musk offered to buy Twitter for $54.20 a share in a filing published Thursday, saying the social media company needs to be transformed privately, a little over a week after revealing a 9.1% stake in the company. Musk’s offer values Twitter at about $43 billion."
"“I invested in Twitter as I believe in its potential to be the platform for free speech around the globe, and I believe free speech is a societal imperative for a functioning democracy,” Musk wrote in a letter sent to Twitter Chairman Bret Taylor and disclosed in a securities filing."
"Twitter shares closed down 1.68% on Thursday. Tesla’s stock dipped more than 3.6% on the news."
"According to Musk, the social media company needs to go private because it can “neither thrive nor serve” free speech in its current state."
"“As a result, I am offering to buy 100% of Twitter for $54.20 per share in cash, a 54% premium over the day before I began investing in Twitter and a 38% premium over the day before my investment was publicly announced,” he wrote. “My offer is my best and final offer and if it is not accepted, I would need to reconsider my position as a shareholder.”"
"He claimed later on Thursday during a talk at TED2022 that he isn’t interested in acquiring Twitter to make money off it and even said he’s not sure if he’ll even be able to buy the company."
"",

"",

""
]